### PR TITLE
tickets/SP-1667: Merge the Times Square OR4 nightsum with the nightly nightsum

### PR DESCRIPTION
**Pull request by ehneilsen**

### CODE REVIEW

**Comment by rhiannonlynne** [comment]
The notebook wasn't loading for me, and I wasn't entirely sure if this was just Times-square being Times-square or if it shouldn't yet (because lsstcomcam is still on its way to being supported). 
Either way - this is great! Much less confusing for finding the reports. 
We might consider deprecating the OR4 report too?

**Review by rhiannonlynne — APPROVED** [review]

**Comment by rhiannonlynne** [comment]
Given how few resources are available for this work, and that getting it out and available asap even if it's not quite right is good, I think a cycle of short iterations and merging is probably the best approach at the moment. 
Feel free to improve and merge as needed.

**Comment by ehneilsen** [comment]
Yes, I am planning on removing the OR4 version before making this a "real" merge request. The current merge request is just intended as a trigger to get Times Square to render it. I don't think it's quite ready to merge yet, but I wanted you to be able to see it. I hope to have it ready to merge today.

**Comment by ehneilsen** [comment]
> Instead of "note", could you move to using `science_program` , `target_name`, `observation_reason`, and `scheduler_note` ? (I know scheduler_note isn't in the ConsDB yet .. ).

Do you have a recommendation for the "correct" one with which to identify DDF fields (for inclusion in the DDF cadence plot)? Note that it will be a easier if there is a column that can be directly mapped from the consdb to an opsim db column, but more complex operations are not, of course, impossible.
Maybe a better approach would be to create a stacker that identifies DDF fields by coordinates (fieldRA and fieldDec) and adds a boolean ddf_field column. After all, I assume the DDF science will still use visits scheduled by the WFD or ToO programs, so perhaps they should be included in the cadence plot as well.

**Comment by rhiannonlynne** [comment]
It might not be handled properly in simulations yet, but the `target_name` should probably be the column, I think. The `scheduler_note` is likely to be similar but may group different DDFs together. 
I am not sure what your goal is to include all visits in the same point on the sky for DDF science, so I think the answer to your question about whether this should be a stacker or not is "it depends"  .. identifing visits that overlap a DDF is already handled in MAF, when running metrics for DDFs, but for the purpose of looking at when visits happened for DDF surveys, I think they should be tagged as such and the plot only include DDF survey specific visits.  
You would not need to make a new stacker, BTW, just use the "labelStacker" with an appropriate footprint for the DDF.

**Pull request merged**
